
--- ERROR LOG ---
Timestamp: 06-082025_11-31-18
Context: table Documents has no column named ErrorLogPath
Exception: Error in create_new_document()
Traceback:
Traceback (most recent call last):
  File "c:\Users\FlowChemIR_User\Desktop\AGS Users\Meg\Automating-inline-IR-analysis-for-optimising-synthetic-reactions-MSc-project-1\db_utils.py", line 154, in create_new_document
    cursor.execute(
    ~~~~~~~~~~~~~~^
        """ INSERT INTO Documents (Name, ExperimentID, ErrorLogPath) VALUES (?, ?, ?)""",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        (name, experiment_id, error_log_path)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
sqlite3.OperationalError: table Documents has no column named ErrorLogPath
------------------------------------------------------------

--- ERROR LOG ---
Timestamp: 06-082025_11-31-36
Context: logs\Unknown_Experiment\error_log_06-08-2025_11-30-48.txt
Exception: User interrupted logging (Ctrl+C)
Traceback:
Traceback (most recent call last):
  File "c:\Users\FlowChemIR_User\Desktop\AGS Users\Meg\Automating-inline-IR-analysis-for-optimising-synthetic-reactions-MSc-project-1\main.py", line 215, in main
    time.sleep(5)
    ~~~~~~~~~~^^^
KeyboardInterrupt
------------------------------------------------------------
